spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 3f8744i11fth1bgrccio1t1nl0
            client-secret: 1su6uobnotiduavu614l6jqr7vj8t0jh9u5ds3qhjcq7sjsc3dhe
            scope:
              - email
              - openid
              - phone
            # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
            # For example: http://localhost:8080/login/oauth2/code/cognito
            # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_74aSy0Zgr
            user-name-attribute: username